name: loops
version: "3.4.4"
license: "GPL-2.0-or-later"
date: 2024-08-29
description: |
    Computing with quasigroups and loops in GAP

authors:
    - name: Gábor Péter Nagy
      url: http://www.math.u-szeged.hu/~nagyg/
    - name: Petr Vojtěchovský
      url: http://www.math.du.edu/~petr/

maintainers:
    - name: Gábor Péter Nagy
      url: http://www.math.u-szeged.hu/~nagyg/
    - name: Petr Vojtěchovský
      url: http://www.math.du.edu/~petr/

GAP: ">=4.8"

www: https://gap-packages.github.io/loops/
readme: README
packageinfo: https://gap-packages.github.io/loops/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/loops/releases/download/v3.4.4/loops-3.4.4.tar.gz

abstract: |
    The LOOPS package provides researchers in nonassociative algebra with a computational tool that integrates standard notions of loop theory with libraries of loops and group-theoretical algorithms of GAP. The package also expands GAP toward nonassociative structures.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    loop, quasigroup, latin square, multiplication group, inner mapping group, Moufang loop, Bol loop, conjugacy closed loop, automorphic loop, Steiner loop, triality, isomorphism of loops, isotopism of loops.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>NV24</span>]   <b class='BibAuthor'>Nagy, G. P. and Vojtěchovský, P.</b>,
     <i class='BibTitle'>loops, Computing with quasigroups and loops in GAP,
             Version 3.4.4</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/loops/">https://gap-packages.github.io/loops/</a></span>.
    </p>
    

bibtex: |
    @misc{ loops,
      author =           {Nagy, G. P. and Vojt{\v e}chovsk{\a'y}, P.},
      title =            {{loops},  Computing with quasigroups and loops in GAP,
                          {V}ersion 3.4.4},
      month =            {Aug},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href          {https://gap-packages.github.io/loops/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{loops/}}},
      keywords =         {loop;  quasigroup; latin square; multiplication group;
                          inner mapping group; Moufang loop; Bol loop; conjugacy
                          closed loop; automorphic loop; Steiner loop; triality;
                          isomorphism of loops; isotopism of loops},
      printedkey =       {NV24}
    }

