name: loops
version: 3.4.3
date: 2022-11-14
description: |
    Computing with quasigroups and loops in GAP

authors:
    - name: Gábor Péter Nagy
      url: http://www.math.u-szeged.hu/~nagyg/
    - name: Petr Vojtěchovský
      url: http://www.math.du.edu/~petr/

maintainers:
    - name: Gábor Péter Nagy
      url: http://www.math.u-szeged.hu/~nagyg/
    - name: Petr Vojtěchovský
      url: http://www.math.du.edu/~petr/

GAP: ">=4.8"

www: https://gap-packages.github.io/loops/
readme: README
packageinfo: https://gap-packages.github.io/loops/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/loops/releases/download/v3.4.3/loops-3.4.3.tar.gz

abstract: |
    The LOOPS package provides researchers in nonassociative algebra with a computational tool that integrates standard notions of loop theory with libraries of loops and group-theoretical algorithms of GAP. The package also expands GAP toward nonassociative structures.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
